### ISSUE TITLE
Images Not Downloading

### ISSUE THREAD

**Issue by notvoid** [Antosik/images-grabber#21]
Installed npm beforehand, restarted. Went to install img-grab as directed but had some permissions errors and ended up having to use sudo, not sure if that's normal. Tried with both pixiv and Twitter and I get prompted with this.

> ListrError: Something went wrong
    at tasks.then (/usr/local/lib/node_modules/images-grabber/node_modules/listr/index.js:102:18)

I'm using Windows 10, Ubuntu terminal, and node.js version 12.18.1 LTS.
Thanks in advance!

**Comment by Antosik** [comment]
Hello!

Thanks for your issue!

Pixiv works fine for me. Seems like you need to authorize to it - pass your username (flag `-U`) and password (flag `-P`).
The Twitter media endpoint was changed, we will see what we can do with it.

**Comment by notvoid** [comment]
Great, thanks. Forgot to mention that I was using the username and password flag as well for pixiv.

**Comment by Antosik** [comment]
@notvoid, I published a beta version with some changes - [3.1.4-beta.0](https://www.npmjs.com/package/images-grabber/v/3.1.4-beta.0).
Can you test it, please?

**Comment by notvoid** [comment]
Just tested. Twitter works great, but I'm still getting the same ListrError with pixiv. I'm gonna assume it's something wrong on my end maybe, since I've been having issues installing and using stuff without sudo.

**Comment by notvoid** [comment]
Figured it out! Was using the url https://pixiv.net/en/users/xx when it should've been pixiv.net/member_illust.php?id=xx

Not sure if all the images are downloading but I'll look into that.

Thanks and sorry for all the trouble!
